### ISSUE TITLE
Robots not moving with cmd_vel (TF's not setting up properly?)

### ISSUE THREAD

**Issue by jrharbin-york** [argenos/sesame_multi_robot_navigation#1]
I have set up everything with ROS Noetic on a new install on Ubuntu 20.04.
I can run the standard tutorials and in the tutorials, drive the Tiago robot around with cmd_vel as shown here:
http://wiki.ros.org/Robots/TIAGo/Tutorials/motions/cmd_vel

In the scenario started with the following:
```
roslaunch exsce_ros scenario.launch scenario_id:=scenario_x
```
The 4 robots show in rviz (I have to click and unclick them to display them), but when sending commands to 
e.g. /tiago1/mobile_baser_controller/cmd_vel there is no response.
Also the costmaps in blue/purple are not shown.
This is probably due to lots of errors at the start related to the TF's:

```
ERROR] [1692701755.825361687, 3.806000000]: Could not find a connection between 'pmb1/map' and 'pmb1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701755.826274040, 3.807000000]: Could not find a connection between 'tiago2/map' and 'tiago2/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701755.827272604, 3.808000000]: Could not find a connection between 'omni1/map' and 'omni1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701755.873319428, 3.854000000]: Could not find a connection between 'tiago1/map' and 'tiago1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701756.025887158, 4.006000000]: Could not find a connection between 'pmb1/map' and 'pmb1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701756.026724031, 4.007000000]: Could not find a connection between 'tiago2/map' and 'tiago2/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701756.027479543, 4.008000000]: Could not find a connection between 'omni1/map' and 'omni1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701756.073640249, 4.054000000]: Could not find a connection between 'tiago1/map' and 'tiago1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701756.225976947, 4.206000000]: Could not find a connection between 'pmb1/map' and 'pmb1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701756.226621359, 4.207000000]: Could not find a connection between 'tiago2/map' and 'tiago2/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701756.227339252, 4.208000000]: Could not find a connection between 'omni1/map' and 'omni1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
[ERROR] [1692701756.273713847, 4.254000000]: Could not find a connection between 'tiago1/map' and 'tiago1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.
```

I also get the error below about the OmniDriveController; but I think this is expected since a component is not included in the public simulation?
http://wiki.ros.org/Robots/TIAGo-OMNI-base/Tutorials/Installation/OMNI_Base_Simulation

```
[ERROR] [1692701759.497413602, 4.859000000]: Could not load controller 'mobile_base_controller' because controller type 'omni_drive_controller/OmniDriveController' does not exist.
[ERROR] [1692701759.497466672, 4.859000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
```

roswtf reports:

Loaded plugin openni2_launch.wtf_plugin
Loaded plugin tf.tfwtf
No package or stack in the current directory
================================================================================
Static checks summary:

No errors or warnings
================================================================================
Beginning tests of your ROS graph. These may take a while...
analyzing graph...
... done analyzing graph
running graph rules...
... done running graph rules
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roswtf/__init__.py", line 224, in _roswtf_main
    p(ctx)
  File "/opt/ros/noetic/lib/python3/dist-packages/openni2_launch/wtf_plugin.py", line 114, in roswtf_plugin_online
    error_rule(r, r[0](ctx), ctx)
  File "/opt/ros/noetic/lib/python3/dist-packages/openni2_launch/wtf_plugin.py", line 85, in sensor_notfound
    devices = _device_notfound_subproc(
  File "/opt/ros/noetic/lib/python3/dist-packages/openni2_launch/wtf_plugin.py", line 58, in _device_notfound_subproc
    for i in df.split('\n'):
TypeError: a bytes-like object is required, not 'str'
a bytes-like object is required, not 'str'

Aborting checks, partial results summary:

Found 2 warning(s).
Warnings are things that may be just fine, but are sometimes at fault
WARNING The following node subscriptions are unconnected:
 * /tiago2/move_base:
   * /tiago2/move_base_simple/goal
   * /tiago2/move_base/TebLocalPlannerROS/obstacles
   * /tiago2/move_base/TebLocalPlannerROS/via_points
 * /rviz:
   * /tiago2/move_base_simple/goal
   * /pmb1/move_base_simple/goal
   * /omni1/move_base_simple/goal
   * /tiago1/waypoint_markers_array
   * /tiago1/map_updates
   * /tiago2/waypoint_markers_array
   * /tiago2/map_updates
   * /pmb1/waypoint_markers_array
   * /pmb1/map_updates
   * /omni1/waypoint_markers_array
   * /omni1/map_updates
 * /pmb1/move_base:
   * /pmb1/move_base_simple/goal
   * /pmb1/move_base/local_costmap/obstacle_sonar_layer/pmb1/sonar_base
   * /pmb1/move_base/TebLocalPlannerROS/obstacles
   * /pmb1/move_base/TebLocalPlannerROS/via_points
 * /omni1/move_base:
   * /omni1/move_base_simple/goal
   * /omni1/move_base/TebLocalPlannerROS/obstacles
   * /omni1/move_base/TebLocalPlannerROS/via_points
 * /launch_scenario:
   * /scenario/test_run/finished
 * /tiago1/head_controller/point_head_action:
   * /tiago1/head_controller/point_head_action/goal
   * /tiago1/head_controller/point_head_action/cancel
 * /tiago1/tf_lookup:
   * /tiago1/tf_lookup/goal
   * /tiago1/tf_lookup/cancel
   * /tiago1/tf_stream/goal
   * /tiago1/tf_stream/cancel
 * /tiago1/twist_mux:
   * /tiago1/key_vel
   * /tiago1/tab_vel
   * /tiago1/marker_vel
   * /tiago1/phone_vel
   * /tiago1/rviz_joy_vel
   * /tiago1/servoing_cmd_vel
   * /tiago1/pause_navigation
   * /tiago1/stop_closing_loop
 * /tiago1/move_group:
   * /tiago1/planning_scene
   * /tiago1/collision_object
   * /tiago1/planning_scene_world
 * /tiago1/hand_grasping_action:
   * /tiago1/hand_controller/follow_joint_trajectory/status
   * /tiago1/hand_controller/follow_joint_trajectory/result
   * /tiago1/hand_controller/follow_joint_trajectory/feedback
   * /tiago1/hand_grasping_action/goal
   * /tiago1/hand_grasping_action/cancel
 * /tiago1/joystick_relay:
   * /tiago1/input_joy/cmd_vel
   * /tiago1/joy_priority_action/goal
   * /tiago1/joy_priority_action/cancel
   * /tiago1/joy_turbo_increase/goal
   * /tiago1/joy_turbo_increase/cancel
   * /tiago1/joy_turbo_decrease/goal
   * /tiago1/joy_turbo_decrease/cancel
   * /tiago1/joy_turbo_angular_increase/goal
   * /tiago1/joy_turbo_angular_increase/cancel
   * /tiago1/joy_turbo_angular_decrease/goal
   * /tiago1/joy_turbo_angular_decrease/cancel
   * /tiago1/joy_turbo_reset/goal
   * /tiago1/joy_turbo_reset/cancel
 * /tiago2/head_controller/point_head_action:
   * /tiago2/head_controller/point_head_action/goal
   * /tiago2/head_controller/point_head_action/cancel
 * /tiago2/tf_lookup:
   * /tiago2/tf_lookup/goal
   * /tiago2/tf_lookup/cancel
   * /tiago2/tf_stream/goal
   * /tiago2/tf_stream/cancel
 * /tiago2/twist_mux:
   * /tiago2/key_vel
   * /tiago2/tab_vel
   * /tiago2/marker_vel
   * /tiago2/phone_vel
   * /tiago2/rviz_joy_vel
   * /tiago2/servoing_cmd_vel
   * /tiago2/pause_navigation
   * /tiago2/stop_closing_loop
 * /tiago2/hand_grasping_action:
   * /tiago2/hand_controller/follow_joint_trajectory/status
   * /tiago2/hand_controller/follow_joint_trajectory/result
   * /tiago2/hand_controller/follow_joint_trajectory/feedback
   * /tiago2/hand_grasping_action/goal
   * /tiago2/hand_grasping_action/cancel
 * /tiago2/joystick_relay:
   * /tiago2/input_joy/cmd_vel
   * /tiago2/joy_priority_action/goal
   * /tiago2/joy_priority_action/cancel
   * /tiago2/joy_turbo_increase/goal
   * /tiago2/joy_turbo_increase/cancel
   * /tiago2/joy_turbo_decrease/goal
   * /tiago2/joy_turbo_decrease/cancel
   * /tiago2/joy_turbo_angular_increase/goal
   * /tiago2/joy_turbo_angular_increase/cancel
   * /tiago2/joy_turbo_angular_decrease/goal
   * /tiago2/joy_turbo_angular_decrease/cancel
   * /tiago2/joy_turbo_reset/goal
   * /tiago2/joy_turbo_reset/cancel
 * /tiago2/move_group:
   * /tiago2/planning_scene
   * /tiago2/collision_object
   * /tiago2/planning_scene_world
 * /pmb1/twist_mux:
   * /pmb1/key_vel
   * /pmb1/tab_vel
   * /pmb1/marker_vel
   * /pmb1/phone_vel
   * /pmb1/rviz_joy_vel
   * /pmb1/servoing_cmd_vel
   * /pmb1/pause_navigation
   * /pmb1/stop_closing_loop
   * /pmb1/emergency_brake
 * /tiago2/amcl:
   * /tiago2/initialpose
 * /omni1/twist_mux:
   * /omni1/key_vel
   * /omni1/tab_vel
   * /omni1/marker_vel
   * /omni1/phone_vel
   * /omni1/rviz_joy_vel
   * /omni1/servoing_cmd_vel
   * /omni1/pause_navigation
   * /omni1/stop_closing_loop
   * /omni1/emergency_brake
 * /omni1/joystick:
   * /omni1/joy/set_feedback
 * /pmb1/joystick_relay:
   * /pmb1/input_joy/cmd_vel
   * /pmb1/joy_priority_action/goal
   * /pmb1/joy_priority_action/cancel
   * /pmb1/joy_turbo_increase/goal
   * /pmb1/joy_turbo_increase/cancel
   * /pmb1/joy_turbo_decrease/goal
   * /pmb1/joy_turbo_decrease/cancel
   * /pmb1/joy_turbo_angular_increase/goal
   * /pmb1/joy_turbo_angular_increase/cancel
   * /pmb1/joy_turbo_angular_decrease/goal
   * /pmb1/joy_turbo_angular_decrease/cancel
   * /pmb1/joy_turbo_reset/goal
   * /pmb1/joy_turbo_reset/cancel
 * /omni1/tf_lookup:
   * /omni1/tf_lookup/goal
   * /omni1/tf_lookup/cancel
   * /omni1/tf_stream/goal
   * /omni1/tf_stream/cancel
 * /pmb1/amcl:
   * /pmb1/initialpose
 * /omni1/amcl:
   * /omni1/initialpose
 * /gazebo:
   * /gazebo/set_link_state
   * /gazebo/set_model_state
   * /tiago1/torso_controller/command
   * /tiago2/torso_controller/command
 * /tiago1/play_motion:
   * /tiago1/play_motion/goal
   * /tiago1/play_motion/cancel
 * /tiago2/play_motion:
   * /tiago2/play_motion/goal
   * /tiago2/play_motion/cancel
 * /tiago2/waypoint_dispatcher:
   * /tiago2/waypoint_dispatcher/goal
   * /tiago2/waypoint_dispatcher/cancel
 * /tiago1/move_base:
   * /tiago1/move_base/TebLocalPlannerROS/obstacles
   * /tiago1/move_base/TebLocalPlannerROS/via_points
 * /omni1/waypoint_dispatcher:
   * /omni1/waypoint_dispatcher/goal
   * /omni1/waypoint_dispatcher/cancel
 * /pmb1/waypoint_dispatcher:
   * /pmb1/waypoint_dispatcher/goal
   * /pmb1/waypoint_dispatcher/cancel
 * /tiago1/waypoint_dispatcher:
   * /tiago1/waypoint_dispatcher/goal
   * /tiago1/waypoint_dispatcher/cancel
WARNING These nodes have died:
 * spawn_robot_localhost_23609_8455803887952607353-90

Found 1 error(s).

ERROR The following nodes should be connected but aren't:
 * /tiago1/move_base->/tiago1/move_base (/tiago1/move_base/local_costmap/footprint)
 * /omni1/move_base->/omni1/move_base (/omni1/move_base/local_costmap/footprint)
 * /omni1/move_base->/omni1/move_base (/omni1/move_base/global_costmap/footprint)
 * /tiago2/move_base->/tiago2/move_base (/tiago2/move_base/global_costmap/footprint)
 * /tiago1/move_base->/tiago1/move_base (/tiago1/move_base/global_costmap/footprint)
 * /pmb1/move_base->/pmb1/move_base (/pmb1/move_base/local_costmap/footprint)
 * /pmb1/move_base->/pmb1/move_base (/pmb1/move_base/global_costmap/footprint)
 * /tiago2/move_base->/tiago2/move_base (/tiago2/move_base/local_costmap/footprint)
```

**Comment by jrharbin-york** [comment]
Actually the robots seem to move properly, if I publish to XXX/key_vel or XXX/nav_vel, it just needed larger values than expected for any motion to be observable.
What are the units (is it degrees for angular rotation, and centimeters for x,y,z?)

Something is still wrong with the coordinate systems, I can see messages like this on the console:
```
[ WARN] [1692712639.121412615, 46.377000000]: The origin for the sensor at (-17.04, -40.14) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712661.924783743, 47.577000000]: The origin for the sensor at (-35.75, 47.89) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712664.056702664, 47.677000000]: The origin for the sensor at (71.24, 31.51) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712680.414390463, 48.577000000]: The origin for the sensor at (-35.58, 47.83) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712682.565976022, 48.677000000]: The origin for the sensor at (69.19, 39.95) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712699.842475880, 49.577000000]: The origin for the sensor at (-32.65, 93.74) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712714.316958399, 50.277000000]: The origin for the sensor at (71.28, 34.11) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712719.871420525, 50.577000000]: The origin for the sensor at (-32.61, 93.97) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712739.634235150, 51.577000000]: The origin for the sensor at (-34.55, 47.45) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712758.823233534, 52.577000000]: The origin for the sensor at (-34.24, 47.22) is out of map bounds. So, the costmap cannot raytrace for it.
[ WARN] [1692712777.715778688, 53.577000000]: The origin for the sensor at (-32.56, 94.98) is out of map bounds. So, the costmap cannot raytrace for it.
```

**Comment by argenos** [comment]
If you cd into your catkin workspace, what is the output of `wstool info -t src`?

**Comment by argenos** [comment]
These in particular should be on a different branch than the official tiago tutorials:

```
Localname                     S SCM Version (Spec)            UID  (Spec)  URI  (Spec) [http(s)://...]
 ---------                     - --- --------------            -----------  ---------------------------
 tiago_simulation                git sesame-devel              1f9d17b6565c git@github.com:argenos/tiago_simulation.git
 tiago_moveit_config             git sesame-devel              5504cc891d5b git@github.com:argenos/tiago_moveit_config.git
 robot_pose                    M git sesame-devel              b8b7c9360378 git@github.com:argenos/robot_pose.git
 pal_navigation_cfg_public       git sesame-devel              f291d87408de git@github.com:argenos/pal_navigation_cfg_public.git
 hector_gazebo                   git sesame-devel              82514a7441cd git@github.com:argenos/hector_gazebo.git
```

I have no tf issues on my setup, but I also don't send command velocities to the robots directly, I only interface with them through move_base

**Comment by jrharbin-york** [comment]
This is the output of wstool info -t src below.
In particular all the ones you mentioned seem to be the same branches and UIDs.

The only difference was I changed some lines in your rosinstall file to use e.g.
https://github.com/argenos/tiago_simulation.git instead of git@github.com:argenos/tiago_simulation.git
because it gave me permission errors. 

Could this be a problem?

As I said in the second comment, the robots do move now under velocity commands, I just had to set velocities on key_vel or nav_vel instead, and use larger values.

I'll try setting move_base goals and robots and see if they work properly.

Thanks for your help.

```
 Localname                     S SCM Version (Spec)            UID  (Spec)  URI  (Spec) [http(s)://...]
 ---------                     - --- --------------            -----------  ---------------------------
 exsce_ros                       git main                      2e80bbca7d29 github.com/hbrs-sesame/exsce_ros.git
 waypoint_dispatcher             git main                      b6597fe27650 github.com/argenos/waypoint_dispatcher.git
 floorplan-dsl-environments      git main                      cec70afda3aa github.com/hbrs-sesame/floorplan-dsl-environments.git
 hector_gazebo                   git sesame-devel              82514a7441cd github.com/argenos/hector_gazebo.git
 sesame_multi_robot_navigation   git main                      3fcea757440b github.com/hbrs-sesame/sesame_multi_robot_navigation.git
 tiago_simulation                git sesame-devel              1f9d17b6565c github.com/argenos/tiago_simulation.git
 tiago_moveit_config             git sesame-devel              5504cc891d5b github.com/argenos/tiago_moveit_config.git
 robot_pose                      git sesame-devel              b8b7c9360378 github.com/argenos/robot_pose.git
 pal_navigation_cfg_public       git sesame-devel              f291d87408de github.com/argenos/pal_navigation_cfg_public.git
 tiago_tutorials                 git noetic-devel              7c6f86d10e58 github.com/pal-robotics/tiago_tutorials.git
 tiago_robot                     git kinetic-devel             3f0f25263146 github.com/pal-robotics/tiago_robot.git
 tiago_navigation                git kinetic-devel             0bedc705944b github.com/pal-robotics/tiago_navigation.git
 tiago_description_calibration   git indigo-devel              b608b8da030d github.com/pal-robotics/tiago_description_calibration.git
 tf_lookup                       git master                    b4f91d32d029 github.com/pal-robotics/tf_lookup.git
 teleop_tools                    git pal-overlay-kinetic-devel 9b42c179afa6 github.com/pal-robotics-forks/teleop_tools.git
 slam_gmapping                   git melodic-devel             0835d19c69da github.com/ros-perception/slam_gmapping.git
 simple_models_robot             git kinetic-devel             568a2f3c6f29 github.com/pal-robotics/simple_models_robot.git
 simple_grasping_action          git master                    f5e353c18407 github.com/pal-robotics/simple_grasping_action.git
 rviz_plugin_covariance          git kinetic-devel             b93e3ecc1411 github.com/pal-robotics/rviz_plugin_covariance.git
 ros_control                     git kinetic-devel             15fffa370b11 github.com/pal-robotics-forks/ros_control.git
 ros_controllers                 git kinetic-devel             d9b716905777 github.com/pal-robotics-forks/ros_controllers.git
 roboticsgroup_gazebo_plugins    git kinetic-devel             bdc61975f998 github.com/pal-robotics-forks/roboticsgroup_gazebo_plugins.git
 pmb2_simulation                 git kinetic-devel             c424da0d17a6 github.com/pal-robotics/pmb2_simulation.git
 pmb2_robot                      git kinetic-devel             912a89e26c43 github.com/pal-robotics/pmb2_robot.git
 pmb2_navigation                 git kinetic-devel             b651414cf218 github.com/pal-robotics/pmb2_navigation.git
 play_motion                     git kinetic-devel             7d8e0b5fdbb2 github.com/pal-robotics/play_motion.git
 pal_wsg_gripper                 git indigo-devel              ee542262a264 github.com/pal-robotics/pal_wsg_gripper
 pal_statistics                  git kinetic-devel             6086bfcfcff4 github.com/pal-robotics/pal_statistics.git
 pal_robotiq_gripper             git master                    4f1b047cc3c1 github.com/pal-robotics/pal_robotiq_gripper.git
 pal_python                      git melodic-devel             2e33adfb1edb github.com/pal-robotics/pal_python.git
 pal_navigation_sm               git master                    3e6ae1082a8f github.com/pal-robotics/pal_navigation_sm.git
 pal_msgs                        git indigo-devel              6fe5c7453951 github.com/pal-robotics/pal_msgs.git
 pal_hardware_interfaces         git indigo-devel              64da44a37714 github.com/pal-robotics/pal_hardware_interfaces.git
 pal_hardware_gazebo             git melodic-devel             320e67210e70 github.com/pal-robotics/pal_hardware_gazebo.git
 pal_gripper                     git kinetic-devel             981421243546 github.com/pal-robotics/pal_gripper.git
 pal_gazebo_worlds               git kinetic-devel             678e1d7675de github.com/pal-robotics/pal_gazebo_worlds.git
 pal_gazebo_plugins              git melodic-devel             5677a5ec7598 github.com/pal-robotics/pal_gazebo_plugins.git
 openslam_gmapping               git melodic-devel             96e52322e51b github.com/ros-perception/openslam_gmapping.git
 omni_base_simulation            git melodic-devel             8786436292e7 github.com/pal-robotics/omni_base_simulation.git
 omni_base_robot                 git melodic-devel             b19a41d52e34 github.com/pal-robotics/omni_base_robot.git
 omni_base_navigation            git melodic-devel             59214e38b3db github.com/pal-robotics/omni_base_navigation.git
 navigation_layers               git noetic                    8899b6e95041 github.com/DLu/navigation_layers.git
 humanoid_msgs                   git master                    6fcf3b6c54bb github.com/ahornung/humanoid_msgs.git
 hey5_description                git master                    6608818d3df3 github.com/pal-robotics/hey5_description.git
 head_action                     git indigo-devel              79e98a8e54b1 github.com/pal-robotics/head_action.git
 gazebo_ros_pkgs                 git noetic-devel              80b1ebef62f9 github.com/pal-robotics-forks/gazebo_ros_pkgs.git
 eband_local_planner             git melodic-devel             02252d0fecd1 github.com/pal-robotics-forks/eband_local_planner.git
 dynamic_introspection           git kinetic-devel             131d9100fd41 github.com/pal-robotics/dynamic_introspection.git
 ddynamic_reconfigure_python     git master                    d1dc50162fb8 github.com/pal-robotics/ddynamic_reconfigure_python
 custom_end_effector             git master                    23da28c6736e github.com/pal-robotics/custom_end_effector.git
 backward_ros                    git kinetic-devel             0eaa66390226 github.com/pal-robotics/backward_ros.git
 aruco_ros                       git noetic-devel              823e1f997b58 github.com/pal-robotics/aruco_ros.git
```

**Comment by argenos** [comment]
> The only difference was I changed some lines in your rosinstall file to use e.g.
https://github.com/argenos/tiago_simulation.git instead of [git@github.com](mailto:git@github.com):argenos/tiago_simulation.git
because it gave me permission errors.
> 
> Could this be a problem?

I don't think so, that's just because I prefer git over ssh. 

Do the errors about TFs disappear eventually? Sometimes it's just a matter of waiting for all the nodes to finish their initialization. 

>  Also the costmaps in blue/purple are not shown.

Does this happen for all robots? Maybe you can share a screenshot of rviz. And just to double-check, would this be the only remaining issue (if sending velocity commands and TF errors are "solved")?

**Comment by jrharbin-york** [comment]
I have sent goal commands to the robots in 'map' frame, via XXX/move_base_simple/goal, and all robots moved successfully to them. They seem to be really slow especially on beginning to move, taking a few minutes to move to the other side of their starting room, but they get there eventually :)

The TF errors do disappear eventually by the time the "Ready" is printed on the console. I think it might just be a matter of the startup delays and some components not being ready?

Thanks for all your help. I will close this issue now, and open another r.e. the costmaps, with a screenshot etc.

**Comment by argenos** [comment]
No need to open another issue, I found the problem and I’ll upload the fixes a bit later today.
